"""add attribution hypotheses"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "c17711a67dbb"
down_revision: str | Sequence[str] | None = "0001_initial"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attribution_hypotheses",
        sa.Column("hypothesis_id", sa.UUID(), nullable=False),
        sa.Column("source_actor_id", sa.String(length=128), nullable=False),
        sa.Column("target_actor_id", sa.String(length=128), nullable=False),
        sa.Column("raw_score", sa.Float(), nullable=False),
        sa.Column("support_score", sa.Float(), nullable=False),
        sa.Column("contradiction_score", sa.Float(), nullable=False),
        sa.Column("final_score", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("evidence_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("explanations_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("hypothesis_id"),
    )
    op.create_index(
        op.f("ix_attribution_hypotheses_source_actor_id"),
        "attribution_hypotheses",
        ["source_actor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attribution_hypotheses_target_actor_id"),
        "attribution_hypotheses",
        ["target_actor_id"],
        unique=False,
    )
    op.create_table(
        "hypothesis_contradictions",
        sa.Column("contradiction_id", sa.UUID(), nullable=False),
        sa.Column("hypothesis_id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.String(length=128), nullable=False),
        sa.Column("contradiction_type", sa.String(length=128), nullable=False),
        sa.Column("severity", sa.Float(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["hypothesis_id"],
            ["attribution_hypotheses.hypothesis_id"],
        ),
        sa.PrimaryKeyConstraint("contradiction_id"),
    )
    op.create_index(
        op.f("ix_hypothesis_contradictions_evidence_id"),
        "hypothesis_contradictions",
        ["evidence_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_hypothesis_contradictions_hypothesis_id"),
        "hypothesis_contradictions",
        ["hypothesis_id"],
        unique=False,
    )
    op.drop_constraint(op.f("artifacts_sha256_key"), "artifacts", type_="unique")
    op.create_index(op.f("ix_artifacts_sha256"), "artifacts", ["sha256"], unique=True)
    op.drop_constraint(op.f("evidence_sha256_key"), "evidence", type_="unique")
    op.drop_index(op.f("ix_evidence_sha256"), table_name="evidence")
    op.create_index(op.f("ix_evidence_sha256"), "evidence", ["sha256"], unique=True)
    op.drop_index(op.f("ix_evidence_derivations_derived"), table_name="evidence_derivations")
    op.drop_index(op.f("ix_evidence_derivations_parent"), table_name="evidence_derivations")
    op.create_index(
        op.f("ix_evidence_derivations_derived_evidence_id"),
        "evidence_derivations",
        ["derived_evidence_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_derivations_parent_evidence_id"),
        "evidence_derivations",
        ["parent_evidence_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_evidence_derivations_parent_evidence_id"), table_name="evidence_derivations"
    )
    op.drop_index(
        op.f("ix_evidence_derivations_derived_evidence_id"), table_name="evidence_derivations"
    )
    op.create_index(
        op.f("ix_evidence_derivations_parent"),
        "evidence_derivations",
        ["parent_evidence_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_derivations_derived"),
        "evidence_derivations",
        ["derived_evidence_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_evidence_sha256"), table_name="evidence")
    op.create_index(op.f("ix_evidence_sha256"), "evidence", ["sha256"], unique=False)
    op.create_unique_constraint(
        op.f("evidence_sha256_key"), "evidence", ["sha256"], postgresql_nulls_not_distinct=False
    )
    op.drop_index(op.f("ix_artifacts_sha256"), table_name="artifacts")
    op.create_unique_constraint(
        op.f("artifacts_sha256_key"), "artifacts", ["sha256"], postgresql_nulls_not_distinct=False
    )
    op.drop_index(
        op.f("ix_hypothesis_contradictions_hypothesis_id"), table_name="hypothesis_contradictions"
    )
    op.drop_index(
        op.f("ix_hypothesis_contradictions_evidence_id"), table_name="hypothesis_contradictions"
    )
    op.drop_table("hypothesis_contradictions")
    op.drop_index(
        op.f("ix_attribution_hypotheses_target_actor_id"), table_name="attribution_hypotheses"
    )
    op.drop_index(
        op.f("ix_attribution_hypotheses_source_actor_id"), table_name="attribution_hypotheses"
    )
    op.drop_table("attribution_hypotheses")
    # ### end Alembic commands ###
