/**
 * What the analysis cannot see.
 *
 * Generated by the scorer that produced the number, one line per blind spot it
 * knows about: what a text sample leaves no trace of, what a behavioural profile
 * cannot tell apart from a shared schedule, and which of the recorded metrics
 * are not the model's output at all. A linkage row with a score and no
 * limitations reads as a measurement with no error bars, which is the one thing
 * these scores are not.
 */

import { DataBlock } from '../DataBlock';
import type { PersonaLinkage } from '../../api/types';

export interface LimitationsPanelProps {
  readonly linkage: PersonaLinkage;
  /** Present on a detail read; names the function that produced the score. */
  readonly scorer?: string | undefined;
}

export function LimitationsPanel({ linkage, scorer }: LimitationsPanelProps) {
  return (
    <DataBlock title="What this analysis cannot see" dense >
      {scorer ? (
        <p className="per-limitations__scorer">
          Score computed by <code>{scorer}</code>. Where no trained pairwise verifier was applied,
          the record says so rather than presenting a probability no model produced.
        </p>
      ) : null}
      {linkage.limitations.length === 0 ? (
        <p className="per-empty">
          No limitations recorded. A score with nothing recorded against it should be treated as
          unexamined rather than clean.
        </p>
      ) : (
        <ol className="per-limitations">
          {linkage.limitations.map((line) => (
            <li key={line}>{line}</li>
          ))}
        </ol>
      )}
    </DataBlock>
  );
}
